//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXPENS
    {
        public int EXPENSEID { get; set; }
        public int ITEMID { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<int> TOTALAMOUNT { get; set; }
        public Nullable<System.DateTime> EXPENSEDATE { get; set; }
    
        public virtual ITEM ITEM { get; set; }
    }
}
