//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ITEM()
        {
            this.ADDSTOCKS = new HashSet<ADDSTOCK>();
            this.EXPENSES = new HashSet<EXPENS>();
        }
    
        public int ITEMID { get; set; }
        public string ITEMNAME { get; set; }
        public Nullable<int> BASEPRICE { get; set; }
        public Nullable<int> SUPPLIERID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADDSTOCK> ADDSTOCKS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXPENS> EXPENSES { get; set; }
        public virtual SUPPLIER SUPPLIER { get; set; }
    }
}
