//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class subcasetype
    {
        public int SubcasetypeId { get; set; }
        public string Subcasetype1 { get; set; }
        public Nullable<int> CaseTypeId { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual CaseType CaseType { get; set; }
    }
}
